CI: try to work around the random errors on win+ARM
When sbt is booting, there is something like this
(not always, but quite frequently):

sbt.internal.ServerAlreadyBootingException: java.io.IOException: Could not create lock for \\.\pipe\sbt-load-1056922235554930886_lock, error 998
sbt thinks that server is already booting because of this exception:
    at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:357)
    at sbt.internal.BootServerSocket.<init>(BootServerSocket.java:296)
    ...

[stressData]